# Generated by Django 6.0.1 on 2026-01-16 14:43

import django.db.models.deletion
import songs.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "unique_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(help_text="歌曲标题", max_length=100)),
                (
                    "audio_file",
                    models.FileField(
                        help_text="音频文件", upload_to=songs.models.get_audio_filename
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="封面图片（可选）",
                        null=True,
                        upload_to=songs.models.get_cover_filename,
                    ),
                ),
                (
                    "netease_url",
                    models.URLField(
                        blank=True, help_text="网易云音乐链接（可选）", null=True
                    ),
                ),
                (
                    "audio_hash",
                    models.CharField(
                        db_index=True,
                        help_text="音频文件 SHA256 hash，用于识别重复",
                        max_length=64,
                    ),
                ),
                ("file_size", models.IntegerField(help_text="音频文件大小（字节）")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="最后更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "歌曲",
                "verbose_name_plural": "歌曲",
                "ordering": ["-id"],
            },
        ),
    ]
