# Generated by Django 6.0.1 on 2026-01-16 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_biddinground_alter_song_user_bid_bidresult"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("under_review", "评分中"),
                            ("reviewed", "已评分"),
                        ],
                        default="draft",
                        help_text="谱面状态",
                        max_length=20,
                    ),
                ),
                (
                    "chart_url",
                    models.URLField(
                        blank=True, help_text="谱面URL（指向外部文件服务器）", null=True
                    ),
                ),
                (
                    "chart_id_external",
                    models.CharField(
                        blank=True,
                        help_text="外部服务器的谱面标识",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, help_text="提交时间", null=True),
                ),
                (
                    "review_completed_at",
                    models.DateTimeField(
                        blank=True, help_text="评分完成时间", null=True
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(default=0, help_text="收到的评分数"),
                ),
                (
                    "total_score",
                    models.IntegerField(
                        default=0, help_text="总评分（用于快速计算平均分）"
                    ),
                ),
                (
                    "average_score",
                    models.FloatField(default=0.0, help_text="平均分（0-50）"),
                ),
                (
                    "bid_result",
                    models.ForeignKey(
                        help_text="对应的竞标结果",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="songs.bidresult",
                    ),
                ),
                (
                    "bidding_round",
                    models.ForeignKey(
                        help_text="所属竞标轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="songs.biddinground",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        help_text="谱面对应的歌曲",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="songs.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="谱面创建者",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "谱面",
                "verbose_name_plural": "谱面",
                "ordering": ["-created_at"],
                "unique_together": {("bidding_round", "user", "song")},
            },
        ),
        migrations.CreateModel(
            name="PeerReviewAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待评分"), ("completed", "已完成")],
                        default="pending",
                        help_text="任务状态",
                        max_length=20,
                    ),
                ),
                (
                    "allocated_at",
                    models.DateTimeField(auto_now_add=True, help_text="分配时间"),
                ),
                (
                    "bidding_round",
                    models.ForeignKey(
                        help_text="所属竞标轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_review_allocations",
                        to="songs.biddinground",
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        help_text="被评分的谱面",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_allocations",
                        to="songs.chart",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="评分者",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_peer_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "互评分配",
                "verbose_name_plural": "互评分配",
                "ordering": ["allocated_at"],
                "unique_together": {("bidding_round", "reviewer", "chart")},
            },
        ),
        migrations.CreateModel(
            name="PeerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(help_text="评分（0-50）")),
                (
                    "comment",
                    models.TextField(blank=True, help_text="评论（可选）", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="评分时间"),
                ),
                (
                    "bidding_round",
                    models.ForeignKey(
                        help_text="所属竞标轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_reviews",
                        to="songs.biddinground",
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        help_text="被评分的谱面",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="songs.chart",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="评分者",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_peer_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "allocation",
                    models.OneToOneField(
                        help_text="对应的分配任务",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="songs.peerreviewallocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "互评记录",
                "verbose_name_plural": "互评记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
