# Generated by Django 6.0.1 on 2026-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0005_alter_chart_bid_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="公告标题", max_length=200)),
                ("content", models.TextField(help_text="公告内容（支持 Markdown）")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("news", "新闻"),
                            ("event", "活动"),
                            ("notice", "通知"),
                        ],
                        default="news",
                        help_text="公告分类",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="优先级，越大越靠前"),
                ),
                ("is_pinned", models.BooleanField(default=False, help_text="是否置顶")),
                ("is_active", models.BooleanField(default=True, help_text="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "ordering": ["-is_pinned", "-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Banner 标题", max_length=100)),
                ("content", models.TextField(help_text="Banner 描述内容")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="背景图片 URL（可选）", null=True
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, help_text="点击跳转链接（可选）", null=True
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="了解更多", help_text="按钮文本", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#409EFF", help_text="背景色", max_length=20
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="优先级，越大越靠前"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banner",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
