# Generated by Django 6.0.1 on 2026-01-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0006_announcement_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='阶段名称，如"竞标期"、"制谱期"', max_length=100
                    ),
                ),
                (
                    "phase_key",
                    models.CharField(
                        help_text="唯一标识符，用于权限绑定。如 bidding、mapping、peer_review",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="阶段描述，显示在主页时间轴"),
                ),
                ("start_time", models.DateTimeField(help_text="阶段开始时间")),
                ("end_time", models.DateTimeField(help_text="阶段结束时间")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="显示顺序（从小到大）"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="是否启用此阶段"),
                ),
                (
                    "page_access",
                    models.JSONField(
                        default=dict,
                        help_text='页面访问权限配置，如 {"home": true, "songs": true, "charts": false, "profile": true}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "比赛阶段",
                "verbose_name_plural": "比赛阶段",
                "ordering": ["order", "start_time"],
            },
        ),
    ]
