# Generated by Django 6.0.1 on 2026-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0007_competitionphase"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionphase",
            name="submissions_type",
            field=models.CharField(
                choices=[("songs", "歌曲数"), ("charts", "谱面数")],
                default="songs",
                help_text="该阶段统计的作品类型（显示在首页）",
                max_length=20,
            ),
        ),
    ]
